version: '3'
services:
  mongodb:
    container_name: mongodb
    build: 
      context: ./
      dockerfile: DockerfileMongo
    image: mongodb
    volumes:
      - mongodbvolume:/data/db
    ports:
    - "27017:27017"
    networks:
    - brIPS
  storage:
    container_name: storage
    image: 5geve/storage
    ports:
    - "8001:8001"
    depends_on:
    - mongodb
    networks:
    - brIPS
    volumes:
    - ./etc:/etc
  msno:
    container_name: msno
    image: 5geve/msno
    ports:
    - "8000:8000"
    depends_on:
    - storage
    networks:
    - brIPS
    volumes:
    - ./etc:/etc
volumes:
  mongodbvolume:
    driver: local
networks:
  brIPS:
    external:
      name: brIPS
