version: '3'
services:
  mongodb:
    build:
      context: ./
      dockerfile: DockerfileMongo
    image: mongodb
    volumes:
      - mongodbvolume:/data/db
    ports:
    - "27017:27017"
  storage:
    build:
      context: ./
      dockerfile: DockerfileStorage
    image: storage_config
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
  msno:
    build:
      context: ./
      dockerfile: DockerfileMSNO
    image: msno_config
    ports:
      - "8000:8000"
    depends_on:
      - storage
volumes:
  mongodbvolume:
    driver: local
