"catalogURL":           "http://10.3.3.30:8083/nsd/v1"
"adaptationLayerURL":   "http://10.3.3.30:80/"
"storageURL":           "http://storage:8001/msno/v1/storage"
"siteInventoryURL":     "http://10.3.3.30:8087"
